<a href="https://colab.research.google.com/github/pushpendram988/pandas/blob/main/Panadas3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Merge

In [4]:
import pandas as pd

var1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2 = pd.DataFrame({"A":[1,2,3,5],"c":[21,22,23,24]})

m = pd.merge(var1,var2,on="A")
m

   A   B   c
0  1  11  21
1  2  12  22
2  3  13  23

In [5]:
pd.merge(var1,var2,how="inner")

   A   B   c
0  1  11  21
1  2  12  22
2  3  13  23

In [6]:
pd.merge(var1,var2,how="right")

   A     B   c
0  1  11.0  21
1  2  12.0  22
2  3  13.0  23
3  5   NaN  24

In [7]:
pd.merge(var1,var2,how="outer")

   A     B     c
0  1  11.0  21.0
1  2  12.0  22.0
2  3  13.0  23.0
3  4  14.0   NaN
4  5   NaN  24.0

In [10]:
import pandas as pd
var3 =pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var4=pd.DataFrame({"A":[1,2,3,5],"B":[21,22,23,24]})
pd.merge(var3,var4,left_index=True,right_index=True)

   A_x  B_x  A_y  B_y
0    1   11    1   21
1    2   12    2   22
2    3   13    3   23
3    4   14    5   24

In [11]:
pd.merge(var3,var4,left_index=True,right_index=True,suffixes=("name","id"))

   Aname  Bname  Aid  Bid
0      1     11    1   21
1      2     12    2   22
2      3     13    3   23
3      4     14    5   24

Concate the Table

In [22]:
import pandas as mahadev

chacha1 = pd.Series([1,2,3,4])
chacha2 = pd.Series([11,12,13,14])

mrityunjay = pd.concat([chacha1,chacha2])

















print("baccha Mahadev kanha ho : Ha chacha bataiye")
print("बच्चा इस को ऐड कर दोगे  : अभी लो चाचा ")
print(mrityunjay)

baccha Mahadev kanha ho : Ha chacha bataiye
बच्चा इस को ऐड कर दोगे  : अभी लो चाचा
0     1
1     2
2     3
3     4
0    11
1    12
2    13
3    14
dtype: int64

In [20]:
pd.merge(var3,var4,left_index=True,right_index=True,suffixes=("name","id"))

   Aname  Bname  Aid  Bid
0      1     11    1   21
1      2     12    2   22
2      3     13    3   23
3      4     14    5   24

Now this can be done by the series also

In [19]:
sr1=pd.Series([1,2,3,4])
sr2= pd.Series([11,12,13,14])
pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
0    11
1    12
2    13
3    14
dtype: int64

In [24]:

d1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2 = pd.DataFrame({"A":[1,2,3,5],"B":[21,22,23,24]})
pd.concat([d1,d2])

   A   B
0  1  11
1  2  12
2  3  13
3  4  14
0  1  21
1  2  22
2  3  23
3  5  24

In [25]:
pd.concat([d1,d2],axis=1)

   A   B  A   B
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  14  5  24

In [26]:
pd.concat([d1,d2],axis=0)

   A   B
0  1  11
1  2  12
2  3  13
3  4  14
0  1  21
1  2  22
2  3  23
3  5  24

In [28]:
d1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2 =pd.DataFrame({"A":[1,2],"C":[21,22]})
pd.concat([d1,d2],axis=1)

   A   B    A     C
0  1  11  1.0  21.0
1  2  12  2.0  22.0
2  3  13  NaN   NaN
3  4  14  NaN   NaN

Join

In [29]:
pd.concat([d1,d2],axis=1 ,join="inner")

   A   B  A   C
0  1  11  1  21
1  2  12  2  22

In [30]:
pd.concat([d1,d2],axis=1,join="outer")

   A   B    A     C
0  1  11  1.0  21.0
1  2  12  2.0  22.0
2  3  13  NaN   NaN
3  4  14  NaN   NaN

Key Parameter

In [31]:

d11 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d22 = pd.DataFrame({"A":[1,2,3,5],"c":[21,22,23,24]})
pd.concat([d11,d22],keys=["d11","d22"])

       A     B     c
d11 0  1  11.0   NaN
    1  2  12.0   NaN
    2  3  13.0   NaN
    3  4  14.0   NaN
d22 0  1   NaN  21.0
    1  2   NaN  22.0
    2  3   NaN  23.0
    3  5   NaN  24.0

In [32]:
pd.concat([d11,d22],axis=1,keys=["d11","d22"])

  d11     d22
    A   B   A   c
0   1  11   1  21
1   2  12   2  22
2   3  13   3  23
3   4  14   5  24

In [34]:

d1 = pd.DataFrame({"A":[1,2]})
d2 = pd.DataFrame({"B":[1,2,3],"c":[21,22,23]})
pd.concat([d1,d2])

     A    B     c
0  1.0  NaN   NaN
1  2.0  NaN   NaN
0  NaN  1.0  21.0
1  NaN  2.0  22.0
2  NaN  3.0  23.0