<a href="https://colab.research.google.com/github/pushpendram988/pandas/blob/main/Panadas4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Merge

In [1]:
import pandas as pd

var1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2 = pd.DataFrame({"A":[1,2,3,5],"c":[21,22,23,24]})

m = pd.merge(var1,var2,on="A")
m

   A   B   c
0  1  11  21
1  2  12  22
2  3  13  23

In [2]:
pd.merge(var1,var2,how="inner")

   A   B   c
0  1  11  21
1  2  12  22
2  3  13  23

In [3]:
pd.merge(var1,var2,how="right")

   A     B   c
0  1  11.0  21
1  2  12.0  22
2  3  13.0  23
3  5   NaN  24

In [4]:
pd.merge(var1,var2,how="outer")

   A     B     c
0  1  11.0  21.0
1  2  12.0  22.0
2  3  13.0  23.0
3  4  14.0   NaN
4  5   NaN  24.0

In [5]:
import pandas as pd
var3 =pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var4=pd.DataFrame({"A":[1,2,3,5],"B":[21,22,23,24]})
pd.merge(var3,var4,left_index=True,right_index=True)

   A_x  B_x  A_y  B_y
0    1   11    1   21
1    2   12    2   22
2    3   13    3   23
3    4   14    5   24

In [6]:
pd.merge(var3,var4,left_index=True,right_index=True,suffixes=("name","id"))

   Aname  Bname  Aid  Bid
0      1     11    1   21
1      2     12    2   22
2      3     13    3   23
3      4     14    5   24

Concate the Table

In [7]:
import pandas as mahadev

chacha1 = pd.Series([1,2,3,4])
chacha2 = pd.Series([11,12,13,14])

mrityunjay = pd.concat([chacha1,chacha2])

















print("baccha Mahadev kanha ho : Ha chacha bataiye")
print("बच्चा इस को ऐड कर दोगे  : अभी लो चाचा ")
print(mrityunjay)

baccha Mahadev kanha ho : Ha chacha bataiye
बच्चा इस को ऐड कर दोगे  : अभी लो चाचा
0     1
1     2
2     3
3     4
0    11
1    12
2    13
3    14
dtype: int64

In [8]:
pd.merge(var3,var4,left_index=True,right_index=True,suffixes=("name","id"))

   Aname  Bname  Aid  Bid
0      1     11    1   21
1      2     12    2   22
2      3     13    3   23
3      4     14    5   24

Now this can be done by the series also

In [9]:
sr1=pd.Series([1,2,3,4])
sr2= pd.Series([11,12,13,14])
pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
0    11
1    12
2    13
3    14
dtype: int64

In [10]:

d1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2 = pd.DataFrame({"A":[1,2,3,5],"B":[21,22,23,24]})
pd.concat([d1,d2])

   A   B
0  1  11
1  2  12
2  3  13
3  4  14
0  1  21
1  2  22
2  3  23
3  5  24

In [11]:
pd.concat([d1,d2],axis=1)

   A   B  A   B
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  14  5  24

In [12]:
pd.concat([d1,d2],axis=0)

   A   B
0  1  11
1  2  12
2  3  13
3  4  14
0  1  21
1  2  22
2  3  23
3  5  24

In [13]:
d1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2 =pd.DataFrame({"A":[1,2],"C":[21,22]})
pd.concat([d1,d2],axis=1)

   A   B    A     C
0  1  11  1.0  21.0
1  2  12  2.0  22.0
2  3  13  NaN   NaN
3  4  14  NaN   NaN

Join

In [14]:
pd.concat([d1,d2],axis=1 ,join="inner")

   A   B  A   C
0  1  11  1  21
1  2  12  2  22

In [15]:
pd.concat([d1,d2],axis=1,join="outer")

   A   B    A     C
0  1  11  1.0  21.0
1  2  12  2.0  22.0
2  3  13  NaN   NaN
3  4  14  NaN   NaN

Key Parameter

In [16]:

d11 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d22 = pd.DataFrame({"A":[1,2,3,5],"c":[21,22,23,24]})
pd.concat([d11,d22],keys=["d11","d22"])

       A     B     c
d11 0  1  11.0   NaN
    1  2  12.0   NaN
    2  3  13.0   NaN
    3  4  14.0   NaN
d22 0  1   NaN  21.0
    1  2   NaN  22.0
    2  3   NaN  23.0
    3  5   NaN  24.0

In [17]:
pd.concat([d11,d22],axis=1,keys=["d11","d22"])

  d11     d22
    A   B   A   c
0   1  11   1  21
1   2  12   2  22
2   3  13   3  23
3   4  14   5  24

In [18]:

d1 = pd.DataFrame({"A":[1,2]})
d2 = pd.DataFrame({"B":[1,2,3],"c":[21,22,23]})
pd.concat([d1,d2])

     A    B     c
0  1.0  NaN   NaN
1  2.0  NaN   NaN
0  NaN  1.0  21.0
1  NaN  2.0  22.0
2  NaN  3.0  23.0

GroupBy in Pandas

In [19]:
import pandas as pd
var = pd.DataFrame({"name":["a","b","c","d","a","c","d","b","a","b","a"],
                   "s1":[11,12,13,14,15,16,17,18,19,20,21],
                   "S2":[21,22,23,24,35,26,32,43,54,67,11] })

In [20]:
var_new= var.groupby("name")
var_new

In [21]:
for xforname,yforvalue in var_new:
  print(xforname)
  print()
  print(yforvalue)
  print()

a

   name  s1  S2
0     a  11  21
4     a  15  35
8     a  19  54
10    a  21  11

b

  name  s1  S2
1    b  12  22
7    b  18  43
9    b  20  67

c

  name  s1  S2
2    c  13  23
5    c  16  26

d

  name  s1  S2
3    d  14  24
6    d  17  32

only one data required

> then only use get_group

In [22]:
var_new.get_group("d")

  name  s1  S2
3    d  14  24
6    d  17  32

In [23]:
var_new.max()

      s1  S2
name
a     21  54
b     20  67
c     16  26
d     17  32

In [24]:
li = list(var_new)
li

[('a',
     name  s1  S2
  0     a  11  21
  4     a  15  35
  8     a  19  54
  10    a  21  11),
 ('b',
    name  s1  S2
  1    b  12  22
  7    b  18  43
  9    b  20  67),
 ('c',
    name  s1  S2
  2    c  13  23
  5    c  16  26),
 ('d',
    name  s1  S2
  3    d  14  24
  6    d  17  32)]

JOin and Append function in Pandas

In [25]:
import pandas as pd

var1 = pd.DataFrame({"a":[1,2,3,4],"b":[11,12,13,14]})
var2= pd.DataFrame({"c":[10,20,30,40],"d":[11,22,33,44]})

var1.join(var2)

   a   b   c   d
0  1  11  10  11
1  2  12  20  22
2  3  13  30  33
3  4  14  40  44

In [26]:
var2= pd.DataFrame({"c":[10,20],"d":[11,22]})
var1.join(var2)

   a   b     c     d
0  1  11  10.0  11.0
1  2  12  20.0  22.0
2  3  13   NaN   NaN
3  4  14   NaN   NaN

In [27]:
import pandas as pd
var1 = pd.DataFrame({"a":[1,2,3,4],"b":[11,12,13,14]},index=["a","b","c","d"])
var2= pd.DataFrame({"c":[10,20],"d":[11,22]},index=["a","b"])
var1.join(var2)

   a   b     c     d
a  1  11  10.0  11.0
b  2  12  20.0  22.0
c  3  13   NaN   NaN
d  4  14   NaN   NaN

In [28]:
var2.join(var1,how="right")

      c     d  a   b
a  10.0  11.0  1  11
b  20.0  22.0  2  12
c   NaN   NaN  3  13
d   NaN   NaN  4  14

In [29]:
var2.join(var1,how="left")

    c   d  a   b
a  10  11  1  11
b  20  22  2  12

In [30]:
var1.join(var2,how="outer")

   a   b     c     d
a  1  11  10.0  11.0
b  2  12  20.0  22.0
c  3  13   NaN   NaN
d  4  14   NaN   NaN

In [31]:
import pandas as pd
var1 = pd.DataFrame({"a":[1,2,3,4],"b":[11,12,13,14]},index=["a","b","c","d"])
var2= pd.DataFrame({"c":[10,20],"b":[11,22]},index=["a","b"])
var1.join(var2,how="outer",lsuffix="_1")

   a  b_1     c     b
a  1   11  10.0  11.0
b  2   12  20.0  22.0
c  3   13   NaN   NaN
d  4   14   NaN   NaN

In [32]:
var2.join(var1,how="inner",lsuffix="_1")

    c  b_1  a   b
a  10   11  1  11
b  20   22  2  12

In [33]:
var1.join(var2,how="outer",lsuffix="_2")

   a  b_2     c     b
a  1   11  10.0  11.0
b  2   12  20.0  22.0
c  3   13   NaN   NaN
d  4   14   NaN   NaN

In [34]:
import pandas as pd
var3 =pd.DataFrame({"a":[1,2,3,4],"b":[11,12,13,14]})
var4=pd.DataFrame({"c":[10,20],"b":[11,22]})

pd.concat([var3,var4],ignore_index=True)

     a   b     c
0  1.0  11   NaN
1  2.0  12   NaN
2  3.0  13   NaN
3  4.0  14   NaN
4  NaN  11  10.0
5  NaN  22  20.0

MELT() Function

In [35]:
import pandas as pd
var = pd.DataFrame({"days":[1,2,3,4,5,6],"eng":[11,12,13,14,15,17],"maths":[17,18,19,20,22,31]}
                   )
var

   days  eng  maths
0     1   11     17
1     2   12     18
2     3   13     19
3     4   14     20
4     5   15     22
5     6   17     31

In [36]:
pd.melt(var)

   variable  value
0      days      1
1      days      2
2      days      3
3      days      4
4      days      5
5      days      6
6       eng     11
7       eng     12
8       eng     13
9       eng     14
10      eng     15
11      eng     17
12    maths     17
13    maths     18
14    maths     19
15    maths     20
16    maths     22
17    maths     31

In [37]:
pd.melt(var,id_vars=["days"])

    days variable  value
0      1      eng     11
1      2      eng     12
2      3      eng     13
3      4      eng     14
4      5      eng     15
5      6      eng     17
6      1    maths     17
7      2    maths     18
8      3    maths     19
9      4    maths     20
10     5    maths     22
11     6    maths     31

In [38]:
pd.melt(var,id_vars=["days"],var_name="python",value_name="marks")

    days python  marks
0      1    eng     11
1      2    eng     12
2      3    eng     13
3      4    eng     14
4      5    eng     15
5      6    eng     17
6      1  maths     17
7      2  maths     18
8      3  maths     19
9      4  maths     20
10     5  maths     22
11     6  maths     31

Pivot Function in Pandas python

In [39]:
import pandas as pd

var = pd.DataFrame({"days":[1,2,3,4,5,6],"st_name":["a","b","c","a","b","c"],"eng":
                    [10,12,14,15,16,18],"maths":[17,18,19,13,14,16]})
var

   days st_name  eng  maths
0     1       a   10     17
1     2       b   12     18
2     3       c   14     19
3     4       a   15     13
4     5       b   16     14
5     6       c   18     16

In [40]:
var.pivot(index="days",columns="st_name")

          eng             maths
st_name     a     b     c     a     b     c
days
1        10.0   NaN   NaN  17.0   NaN   NaN
2         NaN  12.0   NaN   NaN  18.0   NaN
3         NaN   NaN  14.0   NaN   NaN  19.0
4        15.0   NaN   NaN  13.0   NaN   NaN
5         NaN  16.0   NaN   NaN  14.0   NaN
6         NaN   NaN  18.0   NaN   NaN  16.0

In [41]:
var.pivot(index="days",columns="st_name",values="eng")

st_name     a     b     c
days
1        10.0   NaN   NaN
2         NaN  12.0   NaN
3         NaN   NaN  14.0
4        15.0   NaN   NaN
5         NaN  16.0   NaN
6         NaN   NaN  18.0

for mean margin and sum

In [42]:
import pandas as pd

var1 = pd.DataFrame({"days":[1,1,1,1,2,2],"st_name":["a","b","a","a","b","b"],"eng":
                     [10,12,15,14,16,12],"maths":[17,18,19,13,14,16]})
var1

   days st_name  eng  maths
0     1       a   10     17
1     1       b   12     18
2     1       a   15     19
3     1       a   14     13
4     2       b   16     14
5     2       b   12     16

In [43]:
var1.pivot_table(index="st_name",columns="days",aggfunc="prod",margins=True)

             eng                    maths
days           1      2      All        1      2       All
st_name
a         2100.0    NaN     2100   4199.0    NaN      4199
b           12.0  192.0     2304     18.0  224.0      4032
All      25200.0  192.0  4838400  75582.0  224.0  16930368