<a href="https://colab.research.google.com/github/pushpendram988/pandas/blob/main/Pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
dic = {"symbol":[1,2,3,4],"Security":[4,5,6,7],"change":[0,2,3,4]}
var = pd.DataFrame(dic)
var

   symbol  Security  change
0       1         4       0
1       2         5       2
2       3         6       3
3       4         7       4

In [4]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=var)

https://docs.google.com/spreadsheets/d/1Fn9zoTGtOJG2sT_fHOhRAzKh8xCsP-_wPkZv3z_bfx4/edit#gid=0

In [9]:
import pandas as pd
var = pd.read_csv("/content/A_new.csv")
var

   symbol  Security  change
0       1       4.0     0.0
1       2       NaN     2.0
2       3       6.0     3.0
3       4       7.0     NaN

In [8]:
from google.colab import files

print("Please upload the 'A_new.csv' file.")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

Please upload the 'A_new.csv' file.

Saving A_new.csv to A_new.csv
User uploaded file "A_new.csv" with length 48 bytes

After uploading the file, you can now modify the cell `cMr2Nm0bJGiB` to read the file from the Colab environment. The path will typically be `/content/A_new.csv`.

In [10]:
import pandas as pd
var = pd.read_csv("/content/A_new.csv")
var

   symbol  Security  change
0       1       4.0     0.0
1       2       NaN     2.0
2       3       6.0     3.0
3       4       7.0     NaN

In [11]:
var.dropna()

   symbol  Security  change
0       1       4.0     0.0
2       3       6.0     3.0