<a href="https://colab.research.google.com/github/pushpendram988/pandas/blob/main/Pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
dic = {"symbol":[1,2,3,4],"Security":[4,5,6,7],"change":[0,2,3,4]}
var = pd.DataFrame(dic)
var

   symbol  Security  change
0       1         4       0
1       2         5       2
2       3         6       3
3       4         7       4

In [2]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=var)

https://docs.google.com/spreadsheets/d/1vkoWJDCFBIiLOQoOLRZEwGRJ6kuxTLCcKc5S8LFaxOQ/edit#gid=0

In [7]:
import pandas as pd
var = pd.read_csv("/content/A_new.csv")
var

   symbol  Security  change
0       1       4.0     0.0
1       2       NaN     2.0
2       3       6.0     3.0
3       4       7.0     NaN

In [6]:
from google.colab import files

print("Please upload the 'A_new.csv' file.")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

Please upload the 'A_new.csv' file.

Saving A_new.csv to A_new.csv
User uploaded file "A_new.csv" with length 48 bytes

After uploading the file, you can now modify the cell `cMr2Nm0bJGiB` to read the file from the Colab environment. The path will typically be `/content/A_new.csv`.

In [8]:
import pandas as pd
var = pd.read_csv("/content/A_new.csv")
var

   symbol  Security  change
0       1       4.0     0.0
1       2       NaN     2.0
2       3       6.0     3.0
3       4       7.0     NaN

In [9]:
var.dropna(axis=1)

   symbol
0       1
1       2
2       3
3       4

In [10]:
var.dropna(axis =1)

   symbol
0       1
1       2
2       3
3       4

In [11]:
var.dropna(subset=["change"])

   symbol  Security  change
0       1       4.0     0.0
1       2       NaN     2.0
2       3       6.0     3.0

In [12]:
var.dropna(inplace=True)
var

   symbol  Security  change
0       1       4.0     0.0
2       3       6.0     3.0

In [13]:
var.dropna(thresh = 1)

   symbol  Security  change
0       1       4.0     0.0
2       3       6.0     3.0

In [14]:
var

   symbol  Security  change
0       1       4.0     0.0
2       3       6.0     3.0

In [15]:
var.fillna("python")

   symbol  Security  change
0       1       4.0     0.0
2       3       6.0     3.0

In [16]:
var.fillna({"symbol":"python","Security":"java","change":"js"})

   symbol  Security  change
0       1       4.0     0.0
2       3       6.0     3.0

In [17]:
var.fillna(method="ffill")

/tmp/ipykernel_1485/3062787689.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  var.fillna(method="ffill")

   symbol  Security  change
0       1       4.0     0.0
2       3       6.0     3.0

In [18]:
var.fillna(method="bfill")

/tmp/ipykernel_1485/119153051.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  var.fillna(method="bfill")

   symbol  Security  change
0       1       4.0     0.0
2       3       6.0     3.0

In [19]:
var.fillna(method="bfill",axis=1)

/tmp/ipykernel_1485/249782568.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  var.fillna(method="bfill",axis=1)

   symbol  Security  change
0     1.0       4.0     0.0
2     3.0       6.0     3.0

In [21]:
var.bfill(axis=1)

   symbol  Security  change
0     1.0       4.0     0.0
2     3.0       6.0     3.0

In [22]:
var.ffill(axis=1)

   symbol  Security  change
0     1.0       4.0     0.0
2     3.0       6.0     3.0

In [23]:
var.fillna(12,inplace=True)
var

   symbol  Security  change
0       1       4.0     0.0
2       3       6.0     3.0

In [24]:
var
var.fillna("python",limit=2)

   symbol  Security  change
0       1       4.0     0.0
2       3       6.0     3.0

In [25]:
var

   symbol  Security  change
0       1       4.0     0.0
2       3       6.0     3.0

In [26]:
var.fillna("python",limit= 2)

   symbol  Security  change
0       1       4.0     0.0
2       3       6.0     3.0

In [27]:
import pandas as pd

dic = {"symbol":[1,1,2,3],"Security":[12,23,4,1],"change":[12,1,0,0],"total":[0,1,1,23]}

var = pd.DataFrame(dic)
var

   symbol  Security  change  total
0       1        12      12      0
1       1        23       1      1
2       2         4       0      1
3       3         1       0     23

In [28]:
var1 = var.to_csv("new.csv")
var1

In [29]:
var1 = var.to_csv("new.csv",index=False)
var1
var

   symbol  Security  change  total
0       1        12      12      0
1       1        23       1      1
2       2         4       0      1
3       3         1       0     23

In [30]:
var1 = pd.read_csv("new.csv")
var1

   symbol  Security  change  total
0       1        12      12      0
1       1        23       1      1
2       2         4       0      1
3       3         1       0     23

In [31]:
var1

   symbol  Security  change  total
0       1        12      12      0
1       1        23       1      1
2       2         4       0      1
3       3         1       0     23

In [32]:
var1.replace(to_replace=1,value=22)

   symbol  Security  change  total
0      22        12      12      0
1      22        23      22     22
2       2         4       0     22
3       3        22       0     23

In [45]:
d= var1.replace(to_replace=0,value="python")
d

   symbol  Security  change   total
0       1        12      12  python
1       1        23       1       1
2       2         4  python       1
3       3         1  python      23

In [40]:
var1.replace([1,1,2,3],22)

   symbol  Security  change  total
0      22        12      12      0
1      22        23      22     22
2      22         4       0     22
3      22        22       0     23

In [53]:
d.replace("[A-Za-z]","java",regex=True)

   symbol  Security                    change                     total
0       1        12                        12  javajavajavajavajavajava
1       1        23                         1                         1
2       2         4  javajavajavajavajavajava                         1
3       3         1  javajavajavajavajavajava                        23

In [56]:
d.replace("[y]","js",regex =True)

   symbol  Security   change    total
0       1        12       12  pjsthon
1       1        23        1        1
2       2         4  pjsthon        1
3       3         1  pjsthon       23

In [62]:
d.replace({"symbol":'[a-z]'},22,regex=True)

   symbol  Security  change   total
0       1        12      12  python
1       1        23       1       1
2       2         4  python       1
3       3         1  python      23

In [63]:
d.replace(1,method="ffill")

/tmp/ipykernel_1485/1788006687.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  d.replace(1,method="ffill")

   symbol  Security  change   total
0       1        12      12  python
1       1        23      12  python
2       2         4  python  python
3       3         4  python      23

In [65]:
var1.replace(1,method="bfill")

/tmp/ipykernel_1485/1684171772.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var1.replace(1,method="bfill")

   symbol  Security  change  total
0       2        12      12      0
1       2        23       0     23
2       2         4       0     23
3       3         1       0     23

In [66]:
var1.replace(1,method="ffill",limit =2)

/tmp/ipykernel_1485/3095862301.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var1.replace(1,method="ffill",limit =2)

   symbol  Security  change  total
0       1        12      12      0
1       1        23      12      0
2       2         4       0      0
3       3         4       0     23

In [77]:
var1.replace(1,method="ffill",limit =2,inplace=True)
var1

/tmp/ipykernel_1485/4129366040.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var1.replace(1,method="ffill",limit =2,inplace=True)

   symbol  Security  change  total
0       1        12      12      0
1       1        23      12      0
2       2         4       0      0
3       3         4       0     23